# Generated by Django 2.2.7 on 2020-01-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200107_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seccion',
            new_name='Seccion_producto',
        ),
    ]
