# Generated by Django 2.2.7 on 2020-01-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200109_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='', upload_to='productos', verbose_name='Imagen'),
        ),
    ]
