# Generated by Django 2.2.7 on 2020-01-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200109_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='', upload_to='productos/', verbose_name='Imagen'),
        ),
    ]
